version: "3"
services:
    mariadb:
        image: mariadb:buster
        expose:
          - "3306"
        volumes:
          - ../volumes/mariadb:/var/lib/mysql
        env_file:
          - .env
        build:
            context: requirements/mariadb/
    wordpress:
        depends_on:
          - mariadb
        image: wordpress:buster
        expose:
          - "9000"
        volumes:
          - ../volumes/nginx:/var/www/html
        env_file:
          - .env
        build:
            context: requirements/wordpress/
    nginx:
        depends_on:
          - wordpress
        image: nginx:buster
        ports:
          - 443:443
        volumes:
          - ../volumes/nginx:/var/www/html
        env_file:
          - .env
        build:
            context: requirements/nginx/
